### PR TITLE
Enhancement/317-169 Ability to set product-level check-in/out times

### LINKED ISSUE #169: Ability to set Product level Check in and Check out time
#### Affected ticket(s)

926703-zen

#### What I expected

Ability to set Product level Check in and Check out time

#### What happened instead

This is global : 
[Direct Link](http://cld.wthms.co/Ao4mEx+)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### LINKED ISSUE #272: Check in/out times do not display on a per-product basis
Looking at the code WC_Accommodation_Booking_Product_Tabs seems to be very outdated

A bonus would be if we could change the capability through a filter or otherwise to see the global option? In my case, my client will get confused by being able to manage global WP options but I cannot change this without manual edits to the plugin.

#### Affected ticket(s)

N/A

#### What I expected

Check in/out times tab to display

#### What happened instead

Did not display

#### Steps to reproduce the issue

Use the latest WooCommerce, Bookings and Accomodation plugins. Create a new accomodation product.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### LINKED ISSUE #317: Check in/out times per product (or just make it filterable)
We have hit a big problem with the plugin related to check-ins, as some of the accommodation are different types (some glamping, some camping, some bricks & mortar, and all have different check-in / out times.

If you're making code changes in this area then the perfect thing would be to give us per-product check in/out times, but if thats too much coding then adding a filter on the check in out time getter, which also passed in the product id, would give developers the possibility to filter this.

At the moment `class-wc-product-accommodation-booking.php` just has this:

```php
	/**
	 * Get checkin and checkout times.
	 *
	 * @param string $type
	 *
	 * @return string Time, either from options or default
	 */
	public static function get_check_times( $type ) {
		$option = get_option( 'woocommerce_accommodation_bookings_times_settings' );
		switch ( $type ) {
			case 'in':
				return isset( $option['check_in'] ) ? $option['check_in'] : '14:00';
			case 'out':
				return isset( $option['check_out'] ) ? $option['check_out'] : '14:00';
		}

		return '';
	}
```

i could filter the `get_option` call but I don't see how I could detect what product is being queried.

As far as I can tell, this is ignored by the "real code" anyway, as there are comments elsewhere saying its not used, and everything is just counted as one night in this plugin.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by faisal-alvi**
### All Submissions:

* [x] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

This PR introduces a new filter `woocommerce_accommodation_booking_get_check_times` that allows users to filter the check-in/out times per product.

Closes #169,
Closes #317.

### How to test the changes in this Pull Request:
1. Visit WP Admin → Bookings → Settings → Accommodation (tab).
2. Change the check-in time to 9 AM and check-out to 9 AM. (this is just an example)
3. Open any accommodation product and note that when you add it in the cart, it displays the 9 AM as check-in and check-out times.
4. Also, if you are in a storefront theme, you would see “Arriving/leaving” tab on the product page with the same times.
5. Now add the following code in your theme's `functions.php`:
```
add_filter( 'woocommerce_accommodation_booking_get_check_times', function( $check_time, $type, $product_id ) {
	if ( 123 === (int) $product_id ) {
		$check_time = 'in' === $type ? '13:00' : $check_time;
		$check_time = 'out' === $type ? '14:00' : $check_time;
	}

	return $check_time;
}, 10, 3 );
```
6. Make sure to change the product ID in above code from 123 to your accommodation product's ID.
7. Now check again, the check-in time should be 1 PM and check-out time should be 2 PM (because we’ve filtered it using the above code).
8. Try changing the timings in the code and confirm it works as expected.
9. Also, test various places if the filtered timings display correctly. For example, on cart page, check out page, order success page, bookings edit page, etc.

### Other information:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Dev - Added a new filter, `woocommerce_accommodation_booking_get_check_times`, to change the check-in/out timings per product.

### CODE REVIEW

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
QA Report -  Need Fixes ❌ 
---

@faisal-alvi Changed time is working expected on other places except the Booking Edit page. Booking edit page still shows time which is coming from Plugin Global Setting.

Plugin Global Setting-
Screenshot 2023-02-07 at 8 41 06 PM




Edit Booking Screen - 
Screenshot 2023-02-07 at 8 42 04 PM

Order Edit Screen - 

Screenshot 2023-02-07 at 8 44 54 PM




Customer's email Checked ✅ 
Order email  ✅ 
Booking Calendar  ✅ 
Cart ✅  
Checkout ✅ 
Thank you page  ✅ 
My Account Order Page ✅ 
My Account Bookings Page ✅ 



**Next Step-** Moving back to re-fix.

**Comment by faisal-alvi** [comment]
@ankitguptaindia, I have investigated the issue you reported and was able to reproduce it under the following conditions (and also fixed it):

1. Check-in time and check-out time are both set to 10 AM in the settings.
2. A booking is placed without using the filter.
3. Then, a filter is added in the `functions.php` file with a check-in time of 1 PM and a check-out time of 2 PM.
4. When viewing the booking edit screen, the check-in and check-out times are displayed correctly as 10 AM and 10 AM respectively, which is expected because the booking was made before the filter was applied.
5. However, on the order edit screen, the check-in and check-out times in the highlighted box show as 1 PM and 2 PM, which is incorrect and has been fixed.
6. The same issue is observed on the bookings listing page where the start time and end time columns show 1 PM and 2 PM, even though the booking was made for 10 AM and 10 AM. This has also been fixed.

Moving the linked issue tickets back to the QA column (Skipping 10up code re-review as the change looks fine).

**Comment by ankitguptaindia** [comment]
Hi @faisal-alvi 
Currently, the product level check-in and check-out time are visible on the single product page. However, in other places such as My Account, Order Thank You Page, Edit Order Page, etc., the time is still being displayed from the Accommodation Plugin Core Setting.

Steps:

1. Copy the above code snippet from Point-5 and paste in theme's function.php
2. Change Product ID
3. Open a single product page and verify - **Check-in and Check-out ** _(appearing according to filter)_
4. Place a booking
5. Now check **Check-in and Check-out ** time on Order Thank you page and Edit order page
6. Check-in and Check-out times are appearing to the plugin setting.


image

image




https://user-images.githubusercontent.com/6384299/228507915-6990865e-67b5-4c1e-bffd-f6ee43c364ad.mp4



----


**Next Step-** Moving back to re-fix.

**Comment by faisal-alvi** [comment]
@ankitguptaindia thanks for the report. I tested again and the correct timings are displaying for me on product page, cart page, checkout page, order edit page, edit bookings page, my accounts > bookings page, etc.

image

Let's connect 1:1 to discuss this in detail and test together on a call.

**Comment by faisal-alvi** [comment]
@ankitguptaindia As per our discussion, on the order thank you page, the product ID returning to the filter is not an integer, making the condition `false`.

```
if ( 123 === $product_id ) {
	$check_time = 'in' === $type ? '13:00' : $check_time;
	$check_time = 'out' === $type ? '14:00' : $check_time;
}
```

 I've added a fix for it so it will always return the product ID as an integer.

**Comment by ankitguptaindia** [comment]
Thanks for debugging the issue and fix. It is working fine now.  @faisal-alvi

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.2
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.5.1
* PHP: 8.0.22
* Web Server: Nginx
* Browser: Chrome - Version 111.0.5563.64 
* OS: macOS Monterey V 12.3.1
* Git Branch: enhancement/317

</Details>



**Test Results -** 

- Customer's email Checked ✅
- Order email ✅
- Booking Calendar ✅
- Cart ✅
- Checkout ✅
- Thank you page ✅
- My Account Order Page ✅
- My Account Bookings Page ✅
- Single Product ✅ 


**Functional Demo /  Screencast -**

https://screencast-o-matic.com/watch/c0fhIGVaxMI

**Next Step-** Ready to Code Review(Woo)

**Review by ankitguptaindia — APPROVED** [review]

File: includes/class-wc-product-accommodation-booking.php [hunk 1]
```diff
@@ -328,20 +329,36 @@ public function get_blocks_in_range( $start_date, $end_date, $intervals = array(
...
+		/**
+		 * Filter the check-in/out times for a specific product.
+		 *
+		 * @hook woocommerce_accommodation_booking_get_check_times
+		 *
+		 * @param {string} $check_time The check-in/out time stored in the database.
+		 * @param {string} $type       The type, check_in or check_out.
+		 * @param {int}    $product_id The product ID.
+		 *
+		 * @return {string} The filtered/original time.
```
Comment (barryhughes) [inline includes/class-wc-product-accommodation-booking.php]: Looks a little like the style used with JSDoc, but we don't normally wrap the types in `{}` with phpDoc:

```suggestion
		 * @param string $check_time The check-in/out time stored in the database.
		 * @param string $type       The type, check_in or check_out.
		 * @param int    $product_id The product ID.
		 *
		 * @return string The filtered/original time.
```

File: includes/class-wc-product-accommodation-booking.php [hunk 2]
```diff
@@ -328,20 +329,36 @@ public function get_blocks_in_range( $start_date, $end_date, $intervals = array(
...
-	public static function get_check_times( $type ) {
-		$option = get_option( 'woocommerce_accommodation_bookings_times_settings' );
+	public static function get_check_times( $type, $product_id = 0 ) {
+		$option     = get_option( 'woocommerce_accommodation_bookings_times_settings' );
+		$check_time = '';
+
 		switch ( $type ) {
 			case 'in':
-				return isset( $option['check_in'] ) ? $option['check_in'] : '14:00';
+				$check_time = isset( $option['check_in'] ) ? $option['check_in'] : '14:00';
```
Comment (barryhughes) [inline includes/class-wc-product-accommodation-booking.php]: Optional change that could shorten things up a little:

```suggestion
				$check_time = $option['check_in'] ?? '14:00';
```

(This plugin [requires at least PHP 7.0](https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/1.1.39/woocommerce-accommodation-bookings.php#L15), so this should be fine.)

File: includes/class-wc-product-accommodation-booking.php [hunk 3]
```diff
@@ -328,20 +329,36 @@ public function get_blocks_in_range( $start_date, $end_date, $intervals = array(
...
+				break;
 			case 'out':
-				return isset( $option['check_out'] ) ? $option['check_out'] : '14:00';
+				$check_time = isset( $option['check_out'] ) ? $option['check_out'] : '14:00';
```
Comment (barryhughes) [inline includes/class-wc-product-accommodation-booking.php]: Optional change, similar to previous:

```suggestion
				$check_time = $option['check_out'] ?? '14:00';
```

File: includes/class-wc-product-accommodation-booking.php [hunk 4]
```diff
@@ -328,20 +329,36 @@ public function get_blocks_in_range( $start_date, $end_date, $intervals = array(
...
-	 * @param string $type
+	 * @param string $type       The type, check_in or check_out.
+	 * @param int    $product_id The product ID.
 	 *
-	 * @return string Time, either from options or default
+	 * @return string The time, either from options or default or from the filtered value.
 	 */
-	public static function get_check_times( $type ) {
-		$option = get_option( 'woocommerce_accommodation_bookings_times_settings' );
+	public static function get_check_times( $type, $product_id = 0 ) {
```
Comment (barryhughes) [inline includes/class-wc-product-accommodation-booking.php:337]: This might cause difficulties if a third party extends `WC_Product_Accommodation_Booking` and overrides this method (since there will be a signature mismatch). Not sure how likely that is, but it may be worth calling out in release notes/changelog.

File: includes/class-wc-product-accommodation-booking.php [hunk 5]
```diff
@@ -328,20 +329,36 @@ public function get_blocks_in_range( $start_date, $end_date, $intervals = array(
...
-				return isset( $option['check_out'] ) ? $option['check_out'] : '14:00';
+				$check_time = isset( $option['check_out'] ) ? $option['check_out'] : '14:00';
+				break;
 		}
 
-		return '';
+		/**
+		 * Filter the check-in/out times for a specific product.
+		 *
+		 * @hook woocommerce_accommodation_booking_get_check_times
```
Comment (barryhughes) [inline includes/class-wc-product-accommodation-booking.php]: Definitely shouldn't cause any harm if you want to leave this in place, but I'm not sure if any tools actually recognize `@hook` (the automated tooling usually used for building docs, for instance, will figure out that this is associated with an `apply_filters()` call). 

(...and I'm partly posting this comment out of curiosity, to learn if there are cases where it can be helpful.)

**Review by barryhughes — APPROVED** [review]
Thanks! Left some comments, but mostly optional stuff.

**Comment by faisal-alvi** [comment]
@dkotter just a note for when this is merged and released: https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/328#discussion_r1158641852

> This might cause difficulties if a third party extends WC_Product_Accommodation_Booking and overrides this method (since there will be a signature mismatch). Not sure how likely that is, but it may be worth calling out in the release notes/changelog.

Alternatively, we can use `func_get_args()` but we should use it only if there are many third parties extending the class and I'm not sure how many are there.

File: includes/class-wc-product-accommodation-booking.php (hunk 5 above)
Comment (faisal-alvi) [reply includes/class-wc-product-accommodation-booking.php]: Correct, it is used for building docs but as we do not have docs for this plugin right now, I've removed it. https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/328/commits/f10f347f0f1d18514286895f036b21b66b749279

**Review by barryhughes — APPROVED** [review]
Looking good 👍🏼

**Comment by ankitguptaindia** [comment]
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.2
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.7.0
* PHP: 8.0.22 
* Web Server: Nginx
* Browser: Chrome - Version 112

</Details>


Tested with Archive File created via 

```php woorelease.phar build smoke-testing branch URL ```

- Composer version - 2.3.5
- npm version - 6.14.15
- node version - v14.18.0

#### Please note that this plugin is tested with the build created by specified versions of Composer, Node, and NPM. 



**Status-** 

Working as expected. Ready to merge 🚀

File: includes/class-wc-product-accommodation-booking.php [hunk 6]
```diff
@@ -328,20 +329,34 @@ public function get_blocks_in_range( $start_date, $end_date, $intervals = array(
...
+				$check_time = $option['check_out'] ?? '14:00';
+				break;
 		}
 
-		return '';
+		/**
+		 * Filter the check-in/out times for a specific product.
+		 *
+		 * @param string $check_time The check-in/out time stored in the database.
+		 * @param string $type       The type, check_in or check_out.
```
Comment (rtpHarry) [inline includes/class-wc-product-accommodation-booking.php:354]: If I'm reading this correctly, `$type` has values of `in` or `out`, not `check_in` or `check_out`

Comment (faisal-alvi) [reply includes/class-wc-product-accommodation-booking.php:354]: @rtpHarry thanks for the report. We will fix it along with future fixes.
