### PR TITLE
Fix/201 Separate Calendar Design and Availability for Check-in and Check-out Times!

### LINKED ISSUE #201: Fully booked days show as partially booked - Day after booking shows partially booked.
#### Affected ticket(s)

1502723-zen
8433091-hc
2108399-zen

#### What I expected

Let's say I have a Yurt that I rent out using Accommodation Bookings - there is only 1 yurt so only one available room.

If I book a date, say just 1 night, then, come back to the Calendar, the check-in date shows "partially booked" - but it's fully booked:

http://cld.wthms.co/wR5sre
Image link: http://cld.wthms.co/wR5sre

Additionally, the day *after* shows partially booked(same screenshot above). 

I personally think that it doesn't make sense for Accommodation Bookings to consider something 'partially booked' at all. When you're selecting a room you only care about that room being available from check-in time to check-out time. It doesn't matter if someone had the room before you or after you.

It seems like Accommodation Bookings needs to have some extra logic for these scenarios as it appears to just be using Bookings logic which adds the `partial_booked` class to days which are booked and the day after(because technically the booking bleeds into the next day).

#### Steps to reproduce the issue

* Create a new Accommodation Booking product
* Set its "number of rooms available" to 1
* Set a price
* Book a date, say, just 1 night. Complete checkout.
* Go back to the product page and observe that the booked date(which is unavailable) has the `partial_booked` class applied as well as the next day.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### LINKED ISSUE #218: Ability to select starting dates that will not allow for the corresponding minimum days
#### Affected ticket(s)

1999836-zen

Not just should you be able to checkout on a day that's already booked for checkin, if you minimum have to book for 2 consecutive days, you shouldn't be able to be allowed to choose a start day that conflicts with this rule. 

For example:

https://cld.wthms.co/VT4sV6
Link to image here: https://cld.wthms.co/VT4sV6.

In this case:

* 15 shouldn't be allowed to be chosen as a start date
* 14 should be allowed to be chosen as a start date, but then with 16 as an end-date

cc @budzanowski 

Requested to move over here from https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/147#issuecomment-495581094

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### LINKED ISSUE #231: Half booked day displays wrong
#In itself the plugin works fine (see first picture), but I noticed a problem (see second picture)
The problem only occurs when the last day of a booking is the first day of a new calendar column. In this case, the triangle that shows the last day as half booked is displayed upside down. You can still select the last day as the start day of a new booking (see figure three). Therefore the function behind it is correct.  Only the display is wrong. 
Bildschirmfoto 2019-11-21 um 10 21 57

Bildschirmfoto 2019-11-21 um 10 22 05

Bildschirmfoto 2019-11-21 um 10 29 52

I have changed the CSS file of the booking calendar and the representation of the triangles in such a way: 
.wc-bookings-date-picker .ui-datepicker td.partial_booked 
a:before{display:none}

.wc-bookings-date-picker .ui-datepicker td.partial_booked a:after{
	content:"";
	position:absolute;
	right:0;
	bottom:0;
	width:0;
	height:0;
	border-bottom:2.9em solid #C96259;
	border-left:4.9em solid transparent;
	z-index:-10;
	opacity:.95
     }

.wc-bookings-date-picker .ui-datepicker td.fully_booked + td.partial_booked.partial_booked a:after {
	border-bottom: none;
         border-left: none;
         border-top: 2.9em solid #C96259;
         border-right: 4.9em solid transparent;
         left: 0;
         top: 0;
    }

### LINKED ISSUE #235: Fully booked days are showing as available on the accommodation's calendar
#### Affected ticket(s)
2559642-zen
1502723-zen
8433091-hc
2108399-zen

_Note: this is a bit of a duplicate issue to #201, however I was asked to submit a new issue as the previous one has gotten a bit convoluted due to multiple issues being reported in the comment thread._

#### What I expected
On the selected date, there are no accommodation spots available, so I expected to see that date as unavailable/grayed out.

#### What happened instead
On a sold out date, when you view the calendar it looks available, however when you click on the date, you receive a message that there are zero places available and the tooltip says it is partially booked with some availability.

Screen Capture on 2019-12-13 at 14-25-16

Screen Shot 2019-12-13 at 14 26 44

#### Steps to reproduce the issue
1. Create a new Accommodation Booking product
2. Set "number of rooms available" to 1
3. Set a price
4. Choose a date, add to cart, and checkout
5. Go back to the product page and observe that the booked date (which is unavailable) is showing as available until you click on it and the tooltip tells the user that there are bookings still available.

### LINKED ISSUE #243: The starting day (check-in day) of a partial booked day range is not selectable
Affected ticket: 

2750804-zen

**Describe the bug**

This was checked on a product with WooCommerce Bookings and WooCommerce Bookings Accommodation. 

With check-in and check-out times set as 12 PM and 2 PM respectively, when a booking is made for a date range (Say April 15- April 22), April 15 shows as fully booked (incorrect), while April 22 is partially booked (correct).
https://d.pr/i/M0CI1Q 
Full Size: https://d.pr/i/M0CI1Q

HOWEVER, this works fine when using WooCommerce Accommodation Bookings version 1.1.12.

I installed version 1.1.12, and here's a screenshot of the same order:
https://d.pr/i/9PL1JH 
Full Size: https://d.pr/i/9PL1JH

**To Reproduce**
1. Create an accommodation product (make sure WooCommerce, Bookings and Bookings Accommodation are latest versions)
2. Set Check-in and check-out times
3. Make a booking and then check the calendar, the check-in date will show fully booked instead of partially booked. 
4. Install WooCommerce Accommodation Bookings version 1.1.12 and then check the calendar. 

**Expected behavior**
The starting date should be partially booked.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

Setting this to High priority as this would affect many sites using accommodation products.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://woo.local
Site address (URL): http://woo.local
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: wp_
Total Database Size: 36.53MB
Database Data Size: 26.57MB
Database Index Size: 9.96MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.13MB + Engine InnoDB
wp_postmeta: Data: 6.44MB + Index: 4.98MB + Engine InnoDB
wp_posts: Data: 2.36MB + Index: 0.38MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 0.44MB + Index: 0.31MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 3.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 873
aw_workflow: 6
bookable_person: 2
bookable_resource: 7
course: 1
customize_changeset: 2
follow_up_email: 3
global_product_addon: 1
nav_menu_item: 1
page: 19
post: 2
product: 746
product_variation: 63
revision: 18
shop_coupon: 14
shop_order: 98
shop_order_refund: 1
shop_subscription: 17
wc_booking: 23
wc_membership_plan: 1
wc_pickup_location: 1
wcpf_item: 4
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

WooCommerce Accommodation Bookings: by WooCommerce – 1.1.14
WooCommerce Bookings: by WooCommerce – 1.15.12
WooCommerce Subscriptions: by WooCommerce – 3.0.1
WooCommerce: by Automattic – 3.9.2
WordPress Importer: by wordpressdotorg – 0.6.4

### Inactive Plugins (85) ###

AutomateWoo: by WooCommerce – 4.7.4 – Not tested with the active version of WooCommerce
AutomateWoo: by WooCommerce – 4.7.2 – Not tested with the active version of WooCommerce
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Not tested with the active version of WooCommerce
Code Snippets: by Code Snippets Pro – 2.14.0
Customizer Reset: by WPZOOM – 1.0.1
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.1
Follow-Up Emails: by WooCommerce – 4.8.20 – Not tested with the active version of WooCommerce
Gravity Forms: by rocketgenius – 2.4.5.2
Product Filters for WooCommerce: by Nexter – 1.1.16 – Not tested with the active version of WooCommerce
Sensei LMS: by Automattic – 2.2.1 – 2.4.0 is available
Storefront Mega Menus: by WooCommerce – 1.6.2 – Not tested with the active version of WooCommerce
Storefront Parallax Hero: by WooCommerce – 1.5.7
User Switching: by John Blackbourn & contributors – 1.5.3
WooCommerce: by Automattic – 4.0.0-beta.1
WooCommerce Additional Variation Images: by WooCommerce – 1.7.17 – Not tested with the active version of WooCommerce
WooCommerce Additional Variation Images: by WooCommerce – 1.7.17 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.21.0 – Not tested with the active version of WooCommerce
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.4.18 – Not tested with the active version of WooCommerce
WooCommerce All Products For Subscriptions: by SomewhereWarm – 2.4.4 – Not tested with the active version of WooCommerce
WooCommerce Amazon Fulfillment: by Never Settle – 3.2.9 – Not tested with the active version of WooCommerce
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.16 – Not tested with the active version of WooCommerce
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Not tested with the active version of WooCommerce
WooCommerce Bookings Availability: by WooCommerce – 1.1.6
WooCommerce Box Office: by WooCommerce – 1.1.16
WooCommerce Box Office: by WooCommerce – 1.1.15 – Not tested with the active version of WooCommerce
WooCommerce Box Office: by WooCommerce – 1.1.15 – Not tested with the active version of WooCommerce
WooCommerce Brands: by WooCommerce – 1.6.12
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.26 – Not tested with the active version of WooCommerce
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.26 – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.5.7 – Not tested with the active version of WooCommerce
WooCommerce Currency Converter: by WooCommerce – 1.6.16 – Not tested with the active version of WooCommerce
WooCommerce Deposits: by WooCommerce – 1.4.15 – Not tested with the active version of WooCommerce
WooCommerce Dropshipping: by WooCommerce – 1.2.21 – Not tested with the active version of WooCommerce
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.15 – Not tested with the active version of WooCommerce
WooCommerce Email Customizer: by WooCommerce – 1.1.12 – Not tested with the active version of WooCommerce
WooCommerce FedEx Shipping: by WooCommerce – 3.4.24 – Not tested with the active version of WooCommerce
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.9 – Not tested with the active version of WooCommerce
WooCommerce Measurement Price Calculator: by SkyVerge – 3.16.2 – Not tested with the active version of WooCommerce
WooCommerce Measurement Price Calculator: by SkyVerge – 3.17.0 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.16.2 – Not tested with the active version of WooCommerce
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.12 – Not tested with the active version of WooCommerce
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.13
WooCommerce MyGate Gateway: by WooCommerce – 1.2.15 – Not tested with the active version of WooCommerce
WooCommerce New Zealand Post: by WooCommerce – 1.3.6 – Not tested with the active version of WooCommerce
WooCommerce One Page Checkout: by Automattic – 1.7.1 – Not tested with the active version of WooCommerce
WooCommerce Order Barcodes: by Automattic – 1.3.13 – Not tested with the active version of WooCommerce
WooCommerce Order Status Control: by SkyVerge – 1.12.0 – Not tested with the active version of WooCommerce
WooCommerce PayFast Gateway: by WooCommerce – 1.4.14 – Not tested with the active version of WooCommerce
WooCommerce Payment Gateway Based Fees: by InoPlugs – 3.1.10 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.11 – 1.6.20 is available – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18 – 1.6.20 is available – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17 – 1.6.20 is available – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices: by Andrew Benbow – 4.1.10 – Not tested with the active version of WooCommerce
WooCommerce Points and Rewards: by WooCommerce – 1.6.25 – Not tested with the active version of WooCommerce
WooCommerce Pre-Orders: by WooCommerce – 1.5.20 – Not tested with the active version of WooCommerce
WooCommerce Pre-Orders: by WooCommerce – 1.5.20 – Not tested with the active version of WooCommerce
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.8.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.19 – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by SomewhereWarm – 5.13.1 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.30 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.31
WooCommerce Product Reviews Pro: by SkyVerge – 1.15.0 – Not tested with the active version of WooCommerce
WooCommerce Product Vendors: by WooCommerce – 2.1.22 – Not tested with the active version of WooCommerce
WooCommerce Quick View: by WooCommerce – 1.2.6
WooCommerce Sales Report Email: by WooCommerce – 1.1.10 – Not tested with the active version of WooCommerce
WooCommerce Sales Report Email: by WooCommerce – 1.1.10 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooCommerce – 1.6.17 – Not tested with the active version of WooCommerce
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.4 – Not tested with the active version of WooCommerce
WooCommerce Slack: by WooCommerce – 1.1.16
WooCommerce Smart Refunder: by WooCommerce – 1.4.1 – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 2.0.8 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.0 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Automattic – 2.6.5 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Automattic – 2.6.3 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.0 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.0 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.18 – Not tested with the active version of WooCommerce
WooCommerce URL Coupons: by SkyVerge – 2.9.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.35 – Not tested with the active version of WooCommerce
WooCommerce USPS Shipping: by WooCommerce – 4.4.36
WooCommerce Xero Integration: by WooCommerce – 1.7.23 – Not tested with the active version of WooCommerce
Wordfence Security: by Wordfence – 7.4.1
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Mail Logging: by Christian Zöller – 1.9.1
WP Mail Logging: by MailPoet – 1.9.5

### Must Use Plugins (1) ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 4
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Storefront
Version: 2.5.3 – 2.5.5 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://woo.local
Subscription Statuses: wc-active: 1
wc-on-hold: 13
wc-cancelled: 3

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — New York

### Subscriptions by Payment Gateway ###

Direct bank transfer: wc-active: 1
wc-on-hold: 1

Check payments: wc-cancelled: 3
wc-on-hold: 9

other: wc-on-hold: 1

### Payment Gateway Support ###

Direct bank transfer: products
Check payments: products
PayPal: subscriptions
gateway_scheduled_payments
subscription_payment_method_change_customer
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ❌ No

### Action Scheduler ###

Canceled: 21
Oldest: 2020-02-11 05:54:10 +0000
Newest: 2020-02-27 05:43:03 +0000

Complete: 68
Oldest: 2020-01-29 07:54:55 +0000
Newest: 2020-02-28 12:44:43 +0000

Pending: 2
Oldest: 2020-02-29 07:42:12 +0000
Newest: 2020-03-27 05:23:03 +0000

`
```
</details>

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

### LINKED ISSUE #257: Check in date availability
Let's say I make a reservation from 1st to 3rd of August.
That means arrival on 1st and depart on the 3rd.  2 nights stay, which means for the 1st and the 2nd the room is not available for booking.
The calendar shows as red (fully booked) only the 2nd of August.
The check-in date (1st) is still green and says partially booked which is not correct (you cannot book it anyway).
I think this is confusing. Hotels book per night. I think the check-in day should be also red and not available for booking.

edited to add: I used the latest version for the accommodation plugin (1.1.18) and for the woocommerce booking plugin (1.15.23)

### LINKED ISSUE #298: The day is green even if its fully booked!
#### What I expected

The day should be turned red when fully booked.

#### What happened instead

The day kept green even when fully booked. Selecting it shows the error, "There are a maximum of 0 places remaining on XXXX-XX-XX"

_As seen in this image: the 28th should be turned red, but its not._
acom-issue

#### Steps to reproduce the issue

1. Create an accommodation product.
2. Set "Number of rooms available" to "1".
3. Book (for example) the 28th and 29th of the month.
4. (28th is partially booked, so it should still have a green color)
5. Book (for example) the 27th and 28th of the month.
6. (the rest of the 28th is now booked too, so it should turn red! BUT it's still GREEN)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by faisal-alvi**
### All Submissions:

* [x] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

**IMP**: This fix requires changes in the bookings plugin, so the fix will work only when the booking PR https://github.com/woocommerce/woocommerce-bookings/pull/3378 is also used with this PR.

- This PR mainly fixes the issue “fully booked days show as partially booked” as mentioned in #201.
- Introduces separate availability for check-in and check-out days.
- (Scenario before this PR:) For example, the 10th and 11th (1 night) are booked, both days are kept green, and hovering over them shows the days are partially booked. The problem was, that the 10th should not be available (RED) for Check-ins, but it should ALSO be partially booked (GREEN) for Check-outs as someone still can check out on that day!
- This PR fixes that issue by showing the 10th as red (fully booked) when someone is selecting check-in day, and as soon as, the check-in day is selected, the 10th is converted to green!
- There are now 3 types of fully booked days:
    - Fully booked for Check-in days
    - Fully booked for Check-out days
    - Fully booked for days (when a day is fully booked for check-ins and check-outs, both)
- Hovering over “Fully booked for Check-in days”, we’ll see `Available for Check-out only.`

_The 12th is fully booked for check-ins._
image
[image link](https://www.screencast.com/t/kuUsHqcGq)

- Hovering over “Fully booked for Check-out days”, we’ll see `Available for Check-in only.`

_The 18th is fully booked for check-outs._
image
[image link](https://www.screencast.com/t/1BhYfl3KU)

- It also shows `SELECT CHECK-IN` / `SELECT CHECK-OUT` / `SELECTED! RE-SELECT TO CHANGE YOUR CHECK-IN` as per the selection made by the user.

acom-201-1
[image link](https://www.screencast.com/t/Xl5oWSnklvx)

- Issue #231 is also fixed because we are not using the triangle display and its CSS is also completely removed in this PR.
- Issue #235 is also fixed because now we will see fully booked days separately for check-ins and check-outs, which will end the confusion.
- Issue #243 is also fixed because the fully booked check-in day is still selectable for check-outs.
- Issue #257 is also fixed because the check-in days will not be seen as partially booked.
- Issue #298 is also fixed because the fully booked days are now turned red.

Closes #201,
Closes #218,
Closes #231,
Closes #235,
Closes #243,
Closes #257,
Closes #298.

**Question:** When check-in day is selected, why not make the previous days white/not selectable? And why not keep green only the days till the next not-available/red day? Means, why not shrink down the range?
**Answer:** In the current behavior, after check-in and checkout days are selected, a user can still select a new check-in day anywhere on the calendar, which is more user-friendly than shrinking down the calendar days.

### How to test the changes in this Pull Request:

1. Import [booking-product-4128-2022-07-26.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/9189554/booking-product-4128-2022-07-26.zip).
2. The product has 2 resources. The resource “201-res-1” has maximum availability per block is 1. And “201-res-2” has maximum availability per block is 2.
3. At the Front end, see the text on the top of the calendar, “SELECT CHECK-IN”.
4. Select 17th (for example).
5. See the top text changed to “SELECT CHECK-OUT”.
6. Select 18th and book.
7. Now the 17th should be RED and not available to select as a check-in day.
8. Select 15th, see the 17th is now green; as it can be selected as a check-out day. Also, see the 18th is turned red from green; as it is not available to be selected as a check-out day.
9. Try to make bookings with resource 2, which has 2 quantities per block. It should turn the days red only when 2 bookings are made on a single block.
10. Also, check if the fix works when:
    1. Resources are automatically assigned.
    2. No resources used at all.
    3. No resources + Multiple quantities can be booked at the product level.
    4. With/out Persons.
    5. Any type of possible combination in the setting.
11. Please make sure that a normal booking product (not accommodation) is not affected in any way.
12. Also please check each connected issue ticket is resolved by this PR and see if the issues mentioned there are fixed.

**Note for QA:** This PR needs to be checked with https://github.com/woocommerce/woocommerce-bookings/pull/3352 too because it auto-selects the previously selected days when the resource is switched, so we need to make sure this PR works fine with it. This can be tested when all PRs are merged in the testing branch.

### Other information:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Fix - Fully booked days show as partially booked - Day after booking shows partially booked.

### Release Todo Items
- Generate a pot file with `WP CLI`.

### CODE REVIEW

File: includes/class-wc-accommodation-booking-date-picker.php [hunk 1]
```diff
@@ -125,6 +125,70 @@ public function add_partially_booked_dates( $booked_data_array, $product ) {
...
+	 */
+	public function update_fully_booked_dates( $booked_data_array, $product ) {
+		// This function makes sense only for duration type: night.
+		if ( 'night' !== $product->get_duration_unit() ) {
+			return $booked_data_array;
+		}
+
+		// Start and the end dates of all bookings.
+		$check_in_out_times = $this->get_check_in_and_out_times( $product );
+		$res_auto_assign = $product->is_resource_assignment_type( 'automatic' );
```
Comment (dkotter) [inline includes/class-wc-accommodation-booking-date-picker.php]:
```suggestion
		$res_auto_assign    = $product->is_resource_assignment_type( 'automatic' );
```

File: includes/class-wc-accommodation-booking-date-picker.php [hunk 2]
```diff
@@ -125,6 +125,70 @@ public function add_partially_booked_dates( $booked_data_array, $product ) {
...
+					$check_in_time = $product->get_check_times( 'in' );
+					if ( 'in' === $which ) {
+						$check_time = strtotime( '-1 day ' . $check_in_time , $time );
+					} else {
+						$check_time = strtotime( $check_in_time, $time );
+					}
+					$check = date("F j, Y, g:i a", $check_time );
+					// Check available blocks for resource. If some are available that means that the day is not fully booked.
+					$available_on_time = $this->get_product_resource_available_blocks_on_time( $product, $resource_id, $check_time );
+					if( $available_on_time ) {
```
Comment (dkotter) [inline includes/class-wc-accommodation-booking-date-picker.php]:
```suggestion
					if ( $available_on_time ) {
```

File: includes/class-wc-accommodation-booking-date-picker.php [hunk 3]
```diff
@@ -125,6 +125,70 @@ public function add_partially_booked_dates( $booked_data_array, $product ) {
...
+
+						if( isset ( $day_booked_count[ $which ] [ $time ] ) ) {
```
Comment (dkotter) [inline includes/class-wc-accommodation-booking-date-picker.php]:
```suggestion
						if ( isset ( $day_booked_count[ $which ] [ $time ] ) ) {
```

**Review by dkotter — APPROVED** [review]

**Comment by jeffpaul** [comment]
I just added the `DO NOT MERGE` label here as we can not merge/release this until https://github.com/woocommerce/woocommerce-bookings/pull/3378 is merged/released within the Bookings plugin first.  Once 3378 is merged/released, then we can merge/release this Accommodation Bookings PR.

**Comment by ankitguptaindia** [comment]
Hi @faisal-alvi Thanks for the Great work on this PR. Overall this PR works fine. 
I played with some different real life scenario and found some concerns, Please have a look and share your thoughts.

**Point - 1.** Suppose Customer book the room from today. (2 Dec, 22 TO 3 Dec, 22). After Booking, current date has text 'Available for Checkout Only' but checkout is not possible on this day because we can not check-in in past date. 
Technically this is correct but as per User point of view, this is little confusing.

https://user-images.githubusercontent.com/6384299/205318473-bbd07399-f142-45d8-b497-69148b5e383f.mp4



**Point-2.** Suppose a hotel is closed for cleaning on 6 Dec and Availability is set from Booking's Store Availability setting (refer video explanation for more details).
When user try to Check-in on 5th Dec then it allow to check-in but not allow to checkout on 6th. _All good till now._ 
But if user doesn't select checkout date then it is automatically select 6th (which is not availability for checkout due to store availability ) and booking is completed on not available day.  

Is it expected? as I am not sure how accommodation plugin calculate the full day internally.   

**Video Explanation-** 

https://user-images.githubusercontent.com/6384299/205322747-6a80f60b-1c99-4a24-aae2-1a30c3f5a426.mp4


**Issue-3** UI - when changing the resourcing, Check-in-Check-out Text overlap the button.


https://user-images.githubusercontent.com/6384299/205323513-33077613-9ac2-46d5-a412-321d92cfe217.mp4

**Point-4** UX suggestion  - Would be great if we change newly added Check-in/Check-out text to lowe case instead of all in upper case. As we are not showing any other strings in all Uppercase anywhere in this plugin. 

Screenshot 2022-12-02 at 8 41 08 PM



**Point-5** Almost similar to Point 2 but different booking rule: When some day are restricted from Booking "Restrict selectable days?" in Booking setting and customer use those days in between of booking, hose are are getting booked.



https://user-images.githubusercontent.com/6384299/205326444-10b4c506-b4d9-4cce-acb9-7d99d03a9a83.mp4


**Status-** QA in WIP.

**Comment by ankitguptaindia** [comment]
**Point/Issue - 6**
if product has two resource attached and one of the resource has Quantity-2 set. It shows fully booked after booking only one although resource has two Quantity. 


https://user-images.githubusercontent.com/6384299/205691289-59d732e6-b842-48bb-9b59-23616c5a23c6.mp4

Screenshot 2022-12-05 at 10 04 12 PM

**Comment by faisal-alvi** [comment]
@ankitguptaindia  thank you so much for the brief explanations of issues.

**Point - 1:** Yes that's correct, but IMO, we should not add more code just to handle this minor thing as this is not harming the booking process.
**Point - 2:** I think that is expected behavior because the 6th Dec seems to be closed for new check-ins, but existing visitors can check out on that day. If we block the 5th Dec for check-ins, Hotel will lose an extra booking day.
**Issue - 3:** Yes, that is happening in the Storefront theme. I will fix it.
**Point - 4:** Sure, I will do that.
**Point - 5:** Yes, this is the same as point 1, we can consider this in the same new ticket.
**Issue - 6:** I can reproduce this issue, and I will fix it.

**Comment by faisal-alvi** [comment]
@ankitguptaindia The suggestions are implemented and issues are fixed. Moving to the "Code Review 10up" column.

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
> Point - 1: Yes that's correct, but IMO, we should not add more code just to handle this minor thing as this is not harming the booking process.

Okay

> Point - 2: I think that is expected behavior because the 6th Dec seems to be closed for new check-ins, but existing visitors can check out on that day. If we block the 5th Dec for check-ins, Hotel will lose an extra booking day.


Correct but if you notice in the video, 6th Dec is automatically selected. The user is not able to select 6th as the checkout day from the calendar. 
In other words, if the system allows user to book 5th Dec as the check-in date then it should also allow selecting 6th as the check-out day. 

> Issue - 3: Yes, that is happening in the Storefront theme. I will fix it.

Fixed.

> Point - 4: Sure, I will do that.

Fixed

> Point - 5: Yes, this is the same as point 1, we can consider this in the same new ticket.

Do you mean, we will fix this in a separate issue? 


> Issue - 6: I can reproduce this issue, and I will fix it.

This issue has been fixed. 


---

@faisal-alvi I added some concerns above to get your feedback. As this PR has multiples issues connected so I am not moving all back to `In_Progress` column. 
Please let me know if you need more details here.

**Comment by faisal-alvi** [comment]
@ankitguptaindia points 2 and 5 are similar and require further discussion (it's happening in the `trunk`), can you please create a separate ticket for it (mentioning both points in that ticket's description) so that this PR may proceed?

**Comment by ankitguptaindia** [comment]
**Final QA Update-** ✅ 

- Tested this PR after implementing the new logic. Performed as many as possible use cases related to accommodation and booking settings.
- Reported all findings above and those are fixed. (Two concerns will be discussed on a separate ticket, reported here https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/321) 
- Tested PR with and without Resources attached
- Resource auto-assigned and resource manually assigned 
- With and without  Persons
- Calendar visible on click and calendar always visible setting
- Simple Accommodation Product
- Simple Booking Products
- Accommodation Product when Global Availability Rules are defined 
- Issues mentioned in connected tickets with this PR. 
- Other misc use cases and settings. 


**Next Step-** Ready for Woo Code Review. 


cc: @faisal-alvi @jeffpaul

**Review by ankitguptaindia — APPROVED** [review]

**Comment by vikrampm1** [comment]
@jorgeatorres noting that this PR is awaiting your review.

**Review by jorgeatorres — APPROVED** [review]
LGTM as it seems to be working fine. I wonder if it was necessary to push all the codestyle changes as well as those supporting files such as .editorconfig, etc. at the same time that the main changes, which made reviewing a bit more complex.

**Comment by ravinderk** [comment]
> @jorgeatorres noting that this PR is awaiting your review.

@vikrampm1  because of long thread, i missed your comment. I took over this pull request. I refactoring code. I moved this pull request back to `In Progress`.

**Comment by jorgeatorres** [comment]
> I moved this pull request back to In Progress.

@ravinderk: does this mean you're still actively working on this PR? I'm asking because I see some changes were pushed since I last reviewed, but it still shows as approved by me. I'd obviously prefer to re-review once everything's finalized.

**Comment by ravinderk** [comment]
> > I moved this pull request back to In Progress.
> 
> @ravinderk: does this mean you're still actively working on this PR? I'm asking because I see some changes were pushed since I last reviewed, but it still shows as approved by me. I'd obviously prefer to re-review once everything's finalized.

@jorgeatorres Yes, I will ask you once pull request ready.

**Comment by ravinderk** [comment]
FYI, I found out that the selected start date creates an issue when switching resources. I fixed this issue.  This pull request issue is ready to review.

cc: @dkotter

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
QA Note - This PR needs fresh testing again.

Related discussion over Slack - https://10up.slack.com/archives/C01UCQGPBDJ/p1678114532789339

**Comment by ankitguptaindia** [comment]
@ravinderk Tested these new changes and facing some issues as mentioned below. Please import attached product and follow steps shared in the screencast to reproduce those easily. 


1. Import [booking-product-4128-2022-07-26.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/9189554/booking-product-4128-2022-07-26.zip).
2. The product has 2 resources. The resource “201-res-1” has maximum availability per block is 1. And “201-res-2” has maximum availability per block is 2.
3. Book any room for One day
4. Now follow the steps mentioned in the below screencast.



**Issue-1 : An issue with Checkout Date Selection-** 

https://user-images.githubusercontent.com/6384299/228294845-93baa6e8-ed69-4ca9-9a44-4241bd6fa0e9.mp4




-----






**Issue-2 : An issue with Cursor on Checkout Date Selection-**


https://user-images.githubusercontent.com/6384299/228296142-16e27a8a-a7ef-4e2f-a612-789ac11bf508.mp4

----


**Issue-3: Not available date for Checkout, is appearing as active for checkout.** 



https://user-images.githubusercontent.com/6384299/228314439-61e03173-ae47-463a-bd06-a106f048a430.mp4

---

**Issue-4: Customer can book accommodation without selecting Checkout Date. System should not allow checkout without selecting end date.** 


https://user-images.githubusercontent.com/6384299/228321251-89084abb-381b-4517-80cf-1a45ebe25ef8.mp4

----

**Issue-5: Newly added strings `Available for check-out only.` & `Available for check-in only.` are not translatable.** 

Screenshot 2023-03-28 at 11 21 15 PM

---

**Issue-6:  Labels like `Select check-out` & `Selected! Re-select to change your check-in date.` are not translatable. **

image

**Comment by ravinderk** [comment]
@dkotter FYI i made minor changes to pull request to fix issue reported by @ankitguptaindia .
- https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/303/commits/5c5a50a6f18a92452acff0680a4cf99c0143841b
- https://github.com/woocommerce/woocommerce-accommodation-bookings/pull/303/commits/88596ebc01b139fa8e356354aaa2ba29b072f681

@ankitguptaindia i suggest to create another issue for `Issue 4` because I can reproduce same behaviour in `trunk`.

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.2
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.5.1
* PHP: 8.0.22
* Web Server: Nginx
* Browser: Chrome - Version 111.0.5563.64 
* OS: macOS Monterey V 12.3.1
* Git Branch: `fix/accom-201` 

</Details>

**Test Results -** Tested all connected issues and all possible use cases for this change. Found some issues and those have been addressed above. 




**Next Step-** Ready to Code Review(Woo)

**Review by ankitguptaindia — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
@jorgeatorres I wanted to kindly inform you that the PR is now ready for your review once again. At your earliest convenience, would you be able to take a moment to review it and share your valuable feedback? thanks!

**Comment by jorgeatorres** [comment]
@ankitguptaindia @vikrampm1: I believe this PR was accidentally closed by the PR in the Bookings proper. I'm reopening, just in case.

**Comment by vikrampm1** [comment]
Not sure how that this one got closed but thanks for re-opening it @jorgeatorres.

**Review by jorgeatorres — APPROVED** [review]
LGTM. Thanks for all the hard work on this. I know it was a complicated beast.

In the future, I believe doing standards work separate from feature work might make it easier to review things. This fix only touched like 4 or 5 files in reality, but the review involved 17 files. That's a lot of noise.

**Comment by ravinderk** [comment]
> LGTM. Thanks for all the hard work on this. I know it was a complicated beast.
> 
> In the future, I believe doing standards work separate from feature work might make it easier to review things. This fix only touched like 4 or 5 files in reality, but the review involved 17 files. That's a lot of noise.

@jorgeatorres Thank you for your valuable feedback. I am already implementing it for the new pull requests.

**Comment by jeffpaul** [comment]
Note that I removed the `DO NOT MERGE` label as the upstream PR https://github.com/woocommerce/woocommerce-bookings/pull/3378 has been merged and released.

File: assets/js/utils.js [hunk 4]
```diff
@@ -0,0 +1,68 @@
+/* globals jQuery */
+/**
+ * Should return whether the product is a accommodation booking or not.
+ *
+ * @since x.x.x
```
Comment (dkotter) [inline assets/js/utils.js]:
```suggestion
 * @since 1.1.40
```

File: assets/js/utils.js [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+export function is_product_type_accommodation_booking($booking_form) {
+	return $booking_form
+		.closest('.product')
+		.hasClass('product-type-accommodation-booking');
+}
+
+/**
+ * Should return booking form jQuery selector.
+ *
+ * @since x.x.x
```
Comment (dkotter) [inline assets/js/utils.js]:
```suggestion
 * @since 1.1.40
```

File: assets/js/utils.js [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+	// Convert to jQuery selector.
+	$field = get_jquery_element($field);
+
+	return $field.closest('form');
+}
+
+/**
+ * Should return jQuery selector element.
+ *
+ * @since x.x.x
```
Comment (dkotter) [inline assets/js/utils.js]:
```suggestion
 * @since 1.1.40
```

File: assets/js/utils.js [hunk 7]
```diff
@@ -0,0 +1,68 @@
...
+ * @return {jQuery} Return jQuery element.
+ */
+export function get_jquery_element($field) {
+	return jQuery($field);
+}
+
+/**
+ * Should return date type.
+ *
+ * @since x.x.x
```
Comment (dkotter) [inline assets/js/utils.js]:
```suggestion
 * @since 1.1.40
```

File: includes/class-wc-accommodation-booking-date-picker.php [hunk 8]
```diff
@@ -1,4 +1,11 @@
-<?php
+<?php // phpcs:disable WordPress.DateTime.RestrictedFunctions.date_date,WordPress.PHP.StrictInArray.MissingTrueStrict
+/**
+ * This plugin handles the date picker related logic for Accommodation Bookings.
+ *
+ * @package WooCommerce Accommodation Bookings
+ * @since   x.x.x
```
Comment (dkotter) [inline includes/class-wc-accommodation-booking-date-picker.php]:
```suggestion
 * @since   1.1.40
```

File: includes/class-wc-accommodation-booking-date-picker.php [hunk 9]
```diff
@@ -125,30 +137,107 @@ public function add_partially_booked_dates( $booked_data_array, $product ) {
...
+			}
+		}
+
+		return $booked_data_array;
+	}
+
+	/**
+	 * Should return find booked day blocks with additional data.
+	 *
+	 * @since x.x.x
```
Comment (dkotter) [inline includes/class-wc-accommodation-booking-date-picker.php]:
```suggestion
	 * @since 1.1.40
```

File: includes/class-wc-accommodation-bookings-plugin.php [hunk 10]
```diff
@@ -1,4 +1,11 @@
 <?php
+/**
+ * This class is responsible for the plugin's initialization.
+ *
+ * @since x.x.x
```
Comment (dkotter) [inline includes/class-wc-accommodation-bookings-plugin.php]:
```suggestion
 * @since 1.0.2
```

**Comment by ankitguptaindia** [comment]
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.2
* Theme: Storefront Version: 4.2.0
* WooCommerce - Version 7.7.0
* PHP: 8.0.22 
* Web Server: Nginx
* Browser: Chrome - Version 111.0.5563.64


</Details>


Tested with Archive File created via 

```php woorelease.phar build https://github.com/woocommerce/woocommerce-accommodation-bookings/tree/smoke-testing```

- Composer version - 2.3.5
- npm version - 6.14.15
- node version - v14.18.0

#### Please note that this plugin is tested with the build created by specified versions of Composer, Node, and NPM. 

**Issues Tested:**

- https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/243
- https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/235
- https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/231
- https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/218
- https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/201
- https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/257
- https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/298
- Reported issued at the time of QA phase. 

**Status-**Conducted a thorough regression testing which involved checking all the connected issues and performing a comprehensive regression testing for any new issues. As a result, the plugin is now functioning as expected.

**Next Step-** Ready to Merge 🚀 


cc: @vikrampm1 @jeffpaul
