### PR TITLE
Refactor and fix partially booked days on check in/out hook.

### LINKED ISSUE #127: Resource availability calculated incorrectly
#### What I expected

I have 15 rooms. I book 5 for days 1 to 5. All 5 days are shown as partially booked in the calendar. I can still book another 10 rooms for each of the days 1 to 5.

#### What happened instead

I have 15 rooms. I book 5 for days 1 to 5. All 5 days are shown as fully booked in the calendar. I cannot book another room for each of the days 1 to 5.

#### Steps to reproduce the issue

1. Create a resource Rooms and set it to 15.
2. Create accommodation product and assign the resource to the product.
3. Add persons to the product and set each person to be as one booking (person per resource).
4. Booking 1: book rooms for 5 persons for days 1-5.
5. Booking 2: notice the calendar does not allow you to set date for days 1-5.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### LINKED ISSUE #129: Fully booked days not showing correctly when persons are used
If persons are used and counted as bookings, days that are fully booked do not show fully booked.

#### Affected ticket(s)

Found when testing #127.

#### Steps to reproduce the issue

1. Create Accomm product with below settings
1. View product
1. Select date range
1. Increase person count to 15 (to max out availability)
1. Add to cart
1. Calendar will show days as partially booked, not fully booked ❌ 

Image Link: http://cld.wthms.co/pyG1CB

Image Link: http://cld.wthms.co/6TUuZG

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by budzanowski**
Fixes #129 
Fixes #127

#### Changes proposed in this Pull Request:
- If product treats persons as bookings then take persons count into account when calculating fully/partially booked days
- clean results array by removing days with no entries. 

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by budzanowski** [comment]
Changed to In Progress because I have found a bug while working on #127

**Comment by budzanowski** [comment]
Ready for review and testing for #127 and #129

**Comment by jessepearson** [comment]
@budzanowski This is mostly fixed, it seems there's probably a test missing somewhere for when the resources are auto assigned. 

**Before doing the below tests, you need the latest version of [Bookings Helper](https://github.com/woocommerce/bookings-helper/releases) to import the products**

-------
For #127:
1. Used: [booking-product-8746-2017-07-06.json.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/1128615/booking-product-8746-2017-07-06.json.zip)
1. Viewed Product
1. Selected July 17-21
1. Increased Persons to 15
1. Added to cart
1. July 17, 21 show partially booked ✅ 
1. July 18, 19, 20 show as partially booked and should be fully booked ❌ 
1. Updated product to have *Customer selected* resources
1. Viewed product
1. July 17, 21 show partially booked and July 18, 19, 20 show fully booked ✅ 

Additionally:
1. Switch back to **Automatically assigned**
1. Select July 17 and then any other day, except July 21
1. You will get **This block cannot be booked** ✅ 
1.  Select July 17-21 again
1. It allows you to book it again ❌ 

--------

For #129:
1. Used: [booking-product-8749-2017-07-06.json.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/1128638/booking-product-8749-2017-07-06.json.zip)
1. Viewed Product
1. Selected July 17-21
1. Increased Persons to 15
1. Added to cart
1. July 17, 21 show partially booked and July 18, 19, 20 show fully booked ✅

**Comment by budzanowski** [comment]
There is one scary thing I have noticed in the test case for #127 the product is set there to `customer defined blocks of months` but we end up operating on days! as if  it was blocks of days.

**Comment by budzanowski** [comment]
And it is not an Accommodation product :P just Booking.

**Comment by budzanowski** [comment]
My fault. I did not have bookings helper in the latest version so the import was bogus. Retesting again.

**Comment by budzanowski** [comment]
This PR requires https://github.com/woocommerce/woocommerce-bookings/pull/1278 to work correctly.

**Comment by budzanowski** [comment]
PR ready for retesting.

**Comment by jessepearson** [comment]
@budzanowski Like you said, this requires the other PR for this to work, if it is not included there are errors. With that PR, we're good.

-----

For #127:
1. Used branch from: https://github.com/woocommerce/woocommerce-bookings/pull/1278
1. Used: [booking-product-8746-2017-07-06.json.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/1128615/booking-product-8746-2017-07-06.json.zip)
1. Viewed Product
1. Selected July 17-21
1. Leave Persons at 1
1. Added to cart
1. July 17-21 show partially booked ✅ 
1. Selected July 17-21
1. Increased Persons to 114
1. July 17, 21 show partially booked and July 18, 19, 20 show fully booked ✅

**Review by jessepearson — APPROVED** [review]

**Comment by budzanowski** [comment]
This is ready for final review and testing. This version **does not!** require the patch to bookings. It has heavily refactored code influenced greatly by discussion with @bor0 and @dwainm. I have also tried to commented everywhere where it would be useful. Although I wish that this finally works correctly 100% I am also afraid that some cases may have slipped during the heavy refactor.

File: includes/class-wc-accommodation-booking-date-picker.php [hunk 1]
```diff
@@ -60,143 +69,128 @@ public function end_label( $label ) {
...
+	 *    check-in has any avaialble resources it is possible that some booking could end ( had its check-out ) on the
+	 *    check-in date we are testing.
+	 *  - for a check-out date we chack if that date has any available resources. If it does it means that some other
+	 *    booking can start ( can have its check-in ) on the check-out date that we are testing.
+	 * Function works in followin steps:
+	 *  1. gather all check-in and checko-out dates for product
+	 *  2. loop over all dates from (1):
+	 *    a. get all available resources for: day before for check-in and current for check-out
+	 *    b. test if resources are available and if yes than move fully booked day to partially booked days
+	 *
```
Comment (bor0) [inline includes/class-wc-accommodation-booking-date-picker.php]: 👍 docblock

Comment (dwainm) [inline includes/class-wc-accommodation-booking-date-picker.php]: typo: When it is feasible to mark a date partiall booked. Should be "partially".

**Review by dwainm — APPROVED** [review]

**Comment by jessepearson** [comment]
@budzanowski It isn't working right :(

For #127:
1. Used: [booking-product-8746-2017-07-06.json.zip](https://github.com/woocommerce/woocommerce-accommodation-bookings/files/1128615/booking-product-8746-2017-07-06.json.zip)
1. Viewed Product
1. Selected July 24-28
1. Leave Persons at 1
1. Added to cart
1. July 24-28 show partially booked ✅ 
1. Selected July 24-28
1. Increased Persons to 14
1. July 24 shows partially booked and July 25-28 show fully booked ❌ 

July 28 should show partially booked.

**Comment by budzanowski** [comment]
Rebased.

**Comment by jessepearson** [comment]
@budzanowski The tests above now work correctly, but another problem has presented itself. 

1. Used both above products
1. Selected July 23-26
1. Persons set to 1
1. Add to cart
1. July 23-26 show partially booked ✅ 
1. Selected July 25-28
1. Persons set to 14
1. Add to cart
1. July 23-28 show partially booked ❌ 

July 25 & 26 should show fully booked, if you click on them they are not bookable, so that's good :)

**Comment by jessepearson** [comment]
@budzanowski After a close look (thanks to your ping), the above is actually wrong. July 25 & 26 should be partially booked for check out/in. 

I meant to overlap more like July 23-27, then 25-29 so that 26 would be fully booked. I double checked that, and it works 👍

**Comment by budzanowski** [comment]
Hope this works.
