### PR TITLE
Fix missing translation for resource duration display.

### LINKED ISSUE #221: Resource Label Not Translateable
#### Affected ticket(s)
2109372-zen

#### What I expected
To be able to translate my resource labels.

#### What happened instead
This issue: https://github.com/woocommerce/woocommerce-bookings/issues/2191 is the blocker, but since accom adds the night duration unit, I just wanted to open this so it doesn't get forgotten about when the other issue gets fixed.

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ x] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by brezocordero**
Fixes #221  when used with https://github.com/woocommerce/woocommerce-bookings/tree/fix/issue-221

#### Changes proposed in this Pull Request:
Uses new filter in Bookings 'woocommerce_bookings_resource_duration_display_string' to display 'night' resource duration.

How to test:
1. Activate Bookings with the new filter (Branch fix/issue-221) and Accommodation bookings.
2. Build the plugin and translate 'night' into Spanish (Ex: Using Loco Translate)
3. Create an accommodation product (with a standard room rate).
4. Add customer selected resources to the product with a block cost.
AccomodationResource

5. View the product
6. Change the site language to Spanish, view the product and check the resource duration is translated.

AccomodationDuration

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/class-wc-accommodation-booking.php [hunk 1]
```diff
@@ -24,6 +24,7 @@ public function __construct() {
 		add_action( 'woocommerce_new_booking', array( $this, 'update_start_end_time' ) );
 		add_filter( 'woocommerce_data_stores', array( $this, 'register_data_stores' ), 10 );
 		add_filter( 'woocommerce_bookings_apply_multiple_rules_per_block', array( $this, 'disable_overlapping_rates' ), 10, 2 );
+		add_filter( 'woocommerce_bookings_resource_duration_display_string', array( $this, 'accommodation_resource_duration_display_string' ), 10, 2 );
```
Comment (roykho) [inline includes/class-wc-accommodation-booking.php]: I would suggest a change of method name here is because we're already in `accommodation` context so there is no need to prefix it with that. Perhaps `filter_resource_duration_display_string`.

File: includes/class-wc-accommodation-booking.php [hunk 2]
```diff
@@ -164,6 +165,25 @@ public function update_start_end_time( $booking_id ) {
...
+	 *
+	 * @return string $duration_display Duration to display.
+	 */
+	public function accommodation_resource_duration_display_string( $duration_display, $product ) {
+		if ( ! $product || ( 'night' !== $product->get_duration_unit() ) ) {
+			return $duration_display;
+		}
+
+		return __( 'night', 'woocommerce-accommodation-bookings' );
+
```
Comment (roykho) [inline includes/class-wc-accommodation-booking.php]: Probably should remove empty line here before closing brace.

File: includes/class-wc-accommodation-booking.php [hunk 3]
```diff
@@ -164,6 +165,25 @@ public function update_start_end_time( $booking_id ) {
...
+	 *
+	 * @since 1.1.14
+	 *
+	 * @param string $duration_display Duration to display.
+	 * @param object $product          The product we are working with.
+	 *
+	 * @return string $duration_display Duration to display.
+	 */
+	public function accommodation_resource_duration_display_string( $duration_display, $product ) {
+		if ( ! $product || ( 'night' !== $product->get_duration_unit() ) ) {
```
Comment (roykho) [inline includes/class-wc-accommodation-booking.php]: Might be good idea to be more specific here with the `$product` object check. Perhaps use `is_a()` to check for a specific object type.

File: includes/class-wc-accommodation-booking.php (hunk 1 above)
Comment (brezocordero) [reply includes/class-wc-accommodation-booking.php]: Done!

File: includes/class-wc-accommodation-booking.php (hunk 3 above)
Comment (brezocordero) [reply includes/class-wc-accommodation-booking.php]: Done!

File: includes/class-wc-accommodation-booking.php (hunk 2 above)
Comment (brezocordero) [reply includes/class-wc-accommodation-booking.php]: Done!

**Comment by brezocordero** [comment]
@budzanowski the plural on the resource duration happens when there are fixed blocks but that is not the case for accommodation products, that is why I removed the plural on this second implementation.

I might have missed something though, let me know and I will add it back.

**Comment by budzanowski** [comment]
I was thinking about the scenario where we have for example:
Minimum number of nights allowed in a booking = 2
and
Maximum number of nights allowed in a booking = 2
But that does not change the block size as you mentioned which in accommodation is fixed for some reason compared to other booking types.
