### PR TITLE
Fix resource calculation issue.

### LINKED ISSUE #87: Accommodation product + auto-assigned resources = incorrect availability on booking dates
#### Affected ticket(s)

508723-zd-woothemes

#### What I expected

Add a base cost to accommodation products with the use of resources. To do this, I've added one resource on a product with a base cost and quantity = 1:

Screenshot 
Screenshot: http://cld.wthms.co/3ZRu

#### What happened instead

When someone makes a booking on certain dates, and:

- The resource is **customer-selected**, these days show in calendar as not available:

Screenshot 
Screenshot: http://cld.wthms.co/TJXl

- Same setup, resource is **automatically assigned**, all days are available even though I've made a booking:

Screenshot 
Screenshot: http://cld.wthms.co/OX2v

This problem doesn't occur for simple bookable products, resource availability shows correctly in both cases.

#### Steps to reproduce the issue

1. Add two accommodation products with one resource each (quantity = 1).
2. Make the resources on one of these products auto-assigned, on the other one customer-selected.
3. Add two bookings - one for each product - on the same dates.
4. Observe that the first calendar is 100% available, while the other one correctly shows the day that should not be available.

Reproduced both with Bookings 1.9.15 and latest master.

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

### LINKED ISSUE #107: Resource costs not calculated
When testing #87 I found that resource costs were not being added to the booking cost. 

#### Affected ticket(s)

n/a

#### What I expected

Resource costs to be included and to be added to the cart

#### What happened instead

They were not

#### Steps to reproduce the issue

1. Create a new Accomm product with a Standard Room Rate
1. Add a Resource to the product, either Auto or Customer assigned
1. Add either or both a Base or Block cost to the Resource
1. View product and add to cart
1. Only Standard Room Rate will be applied

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

### LINKED ISSUE #110: Today showing green and available when actually booked
#### Affected ticket(s)

566417-zd-woothemes

#### What I expected

"Today" to show as unavailable because there is a booking.

#### What happened instead

Shows green and available. When I click on it, it says "0 days available" (which it should since it's booked)

#### Steps to reproduce the issue

Added by @jessepearson
1. Create an Accomm product, make sure to set the calendar always be viewed
1. View product and add a booking for "today" and a future date
1. View booking in admin under *in-cart* bookings
1. Change start date to "yesterday" or some other past date and change status to **Paid**
1. View product again, and you will see "today" is still available to be clicked on

On this specific instance TODAY, go to https://www.harmonyoutdoorinn.com/product/the-birches/ and notice that April 21st is showing available. It is actually booked per the screenshots attached. I suppose one could test this locally.  I'm on build pr108 of Accommodation Bookings.

**Here's my woothemes ticket with screenshots:**
_WooCommerce Accommodation bookings (dev build woocommerce-accommodation-bookings_pr108) has an issue where today is showing green and available for a product that is not available. The days surrounding today are not available. Screenshots attached._

Post: https://www.harmonyoutdoorinn.com/product/the-birches/

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by bor0**
Alters #108 (add support for resources). Fixes #87, #107, #110.

#### Changes proposed in this Pull Request:
- Need to override a bunch of Bookings methods which depend on type. They were checking `bookings` against `WC_Product_Accommodation_Booking::get_type` which is `accommodation-bookings`.
- Alter availability logic to handle products with resources
- Remove old code which was skipping until check date matches current timestamp (today) to fix #110.

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by jessepearson** [comment]
Calculation is correct, but does this branch include the availability fix, as well?


Image Link: http://cld.wthms.co/kzmI

The booking in the side bar is the 3 partially booked days, and the 29th should be fully booked in this instance.

**Comment by bor0** [comment]
Hm, it does include that fix but it's possible something is missing when resources are set. Will check, nice catch!

**Comment by bor0** [comment]
@jessepearson updated the PR to implement availability for resources as well. It should be good now.

**Comment by bor0** [comment]
Test configurations for cases:
1. Accommodation Booking product with no resources
2. Accommodation Booking product with 2 resources (manually set)
3. Accommodation Booking product with 2 resources (auto set)

Test case 1:
1. Book from day 5 to day 10 (any month).
Expected: 5th and 10th should be partially booked, while 6th until 9th should be fully booked.
2. Book from day 1 to day 5 (same month)
Expected: 1st and 10th should be partially booked, 2nd until 9th should be fully booked.
3. Book from day 10 to day 15 (same month)
Expected: 1st and 15th should be partially booked, 2nd until 14th should be fully booked.

Test case 2:
1. Select first resource
2. Repeat test case 1
3. Select second resource
4. Repeat test case 1
Expected results should be same as test case 1

Test case 3:
1. Repeat each step in test case 1 twice
Expected: Check Bookings in admin that resource is properly allocated for this booking.
2. Repeat test case 1
Expected: Check Bookings in admin that resource is properly allocated for this booking.

**Comment by gedex** [comment]
| Case | Before PR | After PR |
| ----- | ---------- | -------- |
| 1 | ✅ | ✅ |
| 2 | ❌ | ✅ |
| 3 | ❌ | ⚠️ |

@bor0 On test case 3, I found things to confirm here:

* The partially booked style is not displayed after completing the step (5 to 10, 1 to 5, and then 10 5o 15). All days look available. Is this expected?
* After completing the steps twice, the partially booked style appears on day 1 and 15. However, fully booked looks different. It's grey instead of red. Is this expected? See screenshot below.

screen shot 2017-04-25 at 1 04 01 am

**Comment by bor0** [comment]
Hey @gedex,

> The partially booked style is not displayed after completing the step (5 to 10, 1 to 5, and then 10 5o 15). All days look available. Is this expected?
In my opinion yes, because there is another resource that is to be automatically assigned and has availability. This happens even when you do manual change of resources (it shows availability just for that particular source)
> After completing the steps twice, the partially booked style appears on day 1 and 15. However, fully booked looks different. It's grey instead of red. Is this expected? See screenshot below.
I noticed this as well but found to be an issue in the CSS of Bookings. We can file an issue and do a PR style fix.

File: includes/class-wc-product-accommodation-booking-resource.php [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+if ( ! defined( 'ABSPATH' ) ) {
+	exit;
+}
+
+if ( ! class_exists( 'WC_Product_Accommodation_Booking_Resource' ) ) :
+
+/**
+ * Class that creates our new accommodation booking product resource type
+ * Mostly inheirted from WC_Product_Booking_Resource (code reuse!) but overrides a few methods
+ */
```
Comment (gedex) [inline includes/class-wc-product-accommodation-booking-resource.php]: Minor thing. Missing `@since` and `@version`.

Comment (gedex) [inline includes/class-wc-product-accommodation-booking-resource.php]: Typo `inheirted`.
