### PR TITLE
Fix/363 - Fatal Error when WooCommerce is disabled

### LINKED ISSUE #363: Fatal Error when WooCommerce is disabled and Accommodation Bookings is enabled with Booking.
Getting a fatal error when WooCommerce is disabled and Accommodation-Bookings is enabled with Booking.

```
PHP Fatal error:  Uncaught Error: Class "WC_Settings_API" not found in /Users/ank/Local Sites/woolocal/app/public/wp-content/plugins/woocommerce-accommodation-bookings-2/includes/admin/class-wc-accommodation-booking-admin-product-settings.php:8
Stack trace:
#0 /Users/ank/Local Sites/woolocal/app/public/wp-content/plugins/woocommerce-accommodation-bookings-2/includes/class-wc-accommodation-bookings-plugin.php(209): include()
#1 /Users/ank/Local Sites/woolocal/app/public/wp-includes/class-wp-hook.php(310): WC_Accommodation_Bookings_Plugin->admin_includes('')
#2 /Users/ank/Local Sites/woolocal/app/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#3 /Users/ank/Local Sites/woolocal/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /Users/ank/Local Sites/woolocal/app/public/wp-settings.php(632): do_action('init')
#5 /Users/ank/Local Sites/woolocal/app/public/wp-config.php(101): require_once('/Users/ank/Loca...')
#6 /Users/ank/Local Sites/woolocal/app/public/wp-load.php(50): require_once('/Users/ank/Loca...')
#7 /Users/ank/Local Sites/woolocal/app/public/wp-admin/admin.php(34): require_once('/Users/ank/Loca...')
#8 /Users/ank/Local Sites/woolocal/app/public/wp-admin/plugins.php(10): require_once('/Users/ank/Loca...')
#9 {main}
  thrown in /Users/ank/Local Sites/woolocal/app/public/wp-content/plugins/woocommerce-accommodation-bookings-2/includes/admin/class-wc-accommodation-booking-admin-product-settings.php on line 8

```

### **Steps-**

1.  Activate WC, WC Booking and Accommodation-Bookings.
2. Deactivate WC 
3. A fatal error will appear.

Note that if Booking is disabled before the WC then Fatal error will not appear. 

### Environment:

<Details>

### WordPress Environment ###

WordPress address (URL): https://woolocal.local
Site address (URL): https://woolocal.local
WC Version: 8.0.3
REST API Version: ✔ 8.0.3
WC Blocks Version: ✔ 11.0.0
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.0.22
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

</Details>

https://github.com/woocommerce/woocommerce-accommodation-bookings/assets/6384299/b47c78ca-e2fc-4967-8ca5-81df7b4707cd

```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by faisal-alvi**
### All Submissions:

* [ ] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:

This PR adds a check if the `WooCommerce` class exists, if not, it shows a message. This is inspired by the bookings' [message](https://github.com/woocommerce/woocommerce-bookings/blob/abe6d802b7508fe1598406d2cf2143013ad68264/woocommerce-bookings.php#L43).

Closes #363.

### How to test the changes in this Pull Request:

1. Activate WC, WC Booking and Accommodation-Bookings.
2. Deactivate WC
3. A message should appear at the top.
image

### Other information:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Fix - Fatal Error when WooCommerce is disabled.

### CODE REVIEW

File: includes/class-wc-accommodation-bookings-plugin.php [hunk 1]
```diff
@@ -187,6 +187,16 @@ public function load_plugin_textdomain() {
 		load_plugin_textdomain( 'woocommerce-accommodation-bookings', false, dirname( plugin_basename( $this->plugin_file ) ) . '/languages/' );
 	}
 
+	/**
+	 * WooCommerce fallback notice.
+	 *
+	 * @since x.x.x
+	 */
+	public function woocommerce_accommodation_bookings_missing_wc_notice() {
```
Comment (dkotter) [inline includes/class-wc-accommodation-bookings-plugin.php]: Minor thing but because we are in the `WC_Accommodation_Bookings_Plugin` class, we don't need the prefix on this method name. I'd suggest we change this to be just `missing_wc_notice`

**Review by dkotter — CHANGES_REQUESTED** [review]

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.3.1
* Theme: Storefront Version: 4.5.2
* WooCommerce - Version 8.0.3
* PHP: 8.0.21 
* Web Server: Nginx
* Browser: Chrome - Version 116
* OS: macOS Monterey V 12.3.1
* Git Branch: fix/363

</Details>



**Test Results -**  Issue has been fixed. 


**Next Step-** Ready to ~~Code Review(Woo)~~ UAT

**Review by ankitguptaindia — APPROVED** [review]

File: includes/class-wc-accommodation-bookings-plugin.php [hunk 2]
```diff
@@ -187,6 +187,16 @@ public function load_plugin_textdomain() {
 		load_plugin_textdomain( 'woocommerce-accommodation-bookings', false, dirname( plugin_basename( $this->plugin_file ) ) . '/languages/' );
 	}
 
+	/**
+	 * WooCommerce fallback notice.
+	 *
+	 * @since x.x.x
```
Comment (dkotter) [inline includes/class-wc-accommodation-bookings-plugin.php]:
```suggestion
	 * @since 1.2.1
```

**Comment by ankitguptaindia** [comment]
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.3.1
* Theme: Storefront Version: 4.5.2
* WooCommerce - Version 8.1.1
* PHP: 8.0.22 
* Web Server: Nginx
* Browser: Chrome - Version 115


</Details>


Tested with Archive File created via 

```php woorelease.phar build smoke-testing branch _URL_ ```

- Composer version - 2.3.5
- npm version - 8.19.3
- node version - 16.19.1

#### Please note that this plugin has been tested with the build created by the specified versions ☝🏼 of Composer, Node, and NPM. 



**Status-**  Working as expected. Ready to merge 🚀
