### PR TITLE
Fix/issue 223

### LINKED ISSUE #223: Update deprecated functions
Since we've deprecated some functions in Bookings core, we should update them here as well.

### PR DESCRIPTION
**Pull request by roykho**
Fixes #223

#### Changes proposed in this Pull Request:
- Update deprecated function call
- Update build step to be consistent with other extensions.

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by roykho** [comment]
@c-shultz incase you missed this.

File: includes/class-wc-accommodation-booking-date-picker.php [hunk 1]
```diff
@@ -138,11 +138,11 @@ private function get_check_in_and_out_times( $product ) {
 
 		// Using all existing bookings we will calculate start and end time for each booking.
 		// Those times will be considered for switching particular day from full to partially booked days.
-		$existing_bookings  = WC_Bookings_Controller::get_all_existing_bookings( $product );
+		$existing_bookings  = WC_Booking_Data_Store::get_all_existing_bookings( $product );
```
Comment (c-shultz) [inline includes/class-wc-accommodation-booking-date-picker.php]: I think we need to check the Bookings version or the method existence and fallback on the old call in case they don't have the latest Bookings.

File: includes/class-wc-product-accommodation-booking.php [hunk 2]
```diff
@@ -221,7 +221,7 @@ public function get_time_slots( $blocks, $resource_id = 0, $from = 0, $to = 0, $
 
 			list( $interval, $base_interval ) = $intervals;
 
-			$existing_bookings = WC_Bookings_Controller::get_all_existing_bookings( $bookable_product, $from, $to );
+			$existing_bookings = WC_Booking_Data_Store::get_all_existing_bookings( $bookable_product, $from, $to );
```
Comment (c-shultz) [inline includes/class-wc-product-accommodation-booking.php]: Same comment here about Bookings version

File: includes/class-wc-accommodation-booking-date-picker.php (hunk 1 above)
Comment (roykho) [reply includes/class-wc-accommodation-booking-date-picker.php]: Do you think they will update this extension but not bookings core?

Comment (c-shultz) [reply includes/class-wc-accommodation-booking-date-picker.php]: 🤷‍♂ It's possible. Maybe we should just bump this check up: https://github.com/woocommerce/woocommerce-accommodation-bookings/blob/24c8ded076a3e346449219cb7a9b3b71822658ca/includes/class-wc-accommodation-dependencies.php#L72

That would be cleaner than providing backwards compatibility.

**Comment by roykho** [comment]
@c-shultz ok one more round please.
