### PR TITLE
Fix 112 Today showing partially available when not available.

### LINKED ISSUE #112: Today showing partially available when not available
As pointed out [in this comment](https://github.com/woocommerce/woocommerce-accommodation-bookings/issues/110#issuecomment-297024441), if *today* only has **check out** times available, it should show either **fully booked** or unavailable.

#### Affected ticket(s)

n/a

#### What I expected

If *today* is not able to be booked to show either fully booked or unavailable. 

#### What happened instead

*Today* shows as **partially booked** if there is a **check out** time available on it. 

#### Steps to reproduce the issue

1. Create an Accomm product, make sure calendar is viewable by default
1. Select *today* as check in, and a future date as check out
1. Add to cart
1. Page refreshes and *today* is still partially available in the calendar, but when you click you do get the 0 places notice. 

Image Link: http://cld.wthms.co/L4wZ

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by budzanowski**
Fixes #112 .

#### Changes proposed in this Pull Request:
- When `today` is start of the booking it should be marked as fully booked as there are no more actions available for that day. 

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/class-wc-accommodation-booking-date-picker.php [hunk 1]
```diff
@@ -147,6 +147,17 @@ function( $key ) {
 			}
 		}
 
+		//move check in days that occure today to fully booked as they cannot be booked
+		$today = date( 'Y-n-j', current_time( 'timestamp' ) );
+		foreach ( $check_in_out_days[ 'in' ] as $reasource => $days ) {
```
Comment (bor0) [inline includes/class-wc-accommodation-booking-date-picker.php]: `reasource`

**Comment by jessepearson** [comment]
@budzanowski Works for me 👍 

**Note:** If the product created in the test below has an Availability of 2, the *today* still shows fully booked if only 1 of the blocks are taken. I believe this is related to #120, though. 

----

1. Created an Accomm product
1. Selected *today* as check in, and a future date as check out
1. Added to cart
1. Page refreshed and *today* is not available in the calendar ✅
